# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bb1fc6899fdc644ef4a27d4985de9a5c1c7fbc4e77d5caf408d943ff79b10d95e2786a4486c23178a6935b2b51d3cc5588319d248732c6122f5ad769d0278c1

test:
  secret_key_base: 3a39a218f00bd427c1486713d29a0f4ac729dd86b6ac909af3bc8e4d4d56fb9af15fc1edb9dcc2d5659fcde08636d5a37afea17141fcd85ef2431bf34aa12c59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
